"""Repository QA checks in the spirit of Aqua.jl's tests (Python port).

Aqua.jl tests the *quality* of a Julia package's metadata and public API:
dependency integrity, absence of undefined imports, and public-API
consistency. This module brings the same ideas to a Python project:

- every module under the package directory imports cleanly;
- the public API declared in ``__all__`` actually exists on the package;
- no module imports a missing *internal* sibling (dependency completeness
  against ``pyproject.toml`` is deptry's static job).
"""

import importlib
import pkgutil
from pathlib import Path
from typing import cast

import python_copier_template_example as pkg

TOP = Path(__file__).resolve().parent.parent
PKG_DIR = TOP / "src/python_copier_template_example"

# _version.py is generated by setuptools-scm at build time.
_EXCLUDED = {"python_copier_template_example._version"}


def _package_modules() -> list[str]:
    """Dotted names of every importable module under the package directory."""
    # The magic trailing comma keeps this call expanded, which in turn keeps
    # the generator expanded: without it ruff's formatter collapses the whole
    # `sorted(...)` onto one line whenever the package name is short enough,
    # and the shipped file is then unformatted at line-length 120.
    return sorted(
        info.name
        for info in pkgutil.walk_packages(
            [str(PKG_DIR)],
            prefix="python_copier_template_example.",
        )
        if info.name not in _EXCLUDED
    )


def test_every_module_imports() -> None:
    """Importing any module in the package must not raise."""
    for name in _package_modules():
        importlib.import_module(name)


def test_public_api_declared_in_all_is_importable() -> None:
    """Names in __all__ resolve to real attributes of the package."""
    # getattr returns Any; cast to a concrete tuple so the QA test itself
    # stays clean under basedpyright (reportAny / reportUnknownVariableType).
    all_names = cast("tuple[str, ...]", getattr(pkg, "__all__", ()))
    for name in all_names:
        assert hasattr(pkg, name), f"{name!r} missing from the package"


def test_no_obviously_undefined_internal_imports() -> None:
    """A package module must not import a sibling module that does not exist.

    Importing every module (test_every_module_imports) already fails on a
    missing *third-party* dependency; this adds a guard for missing
    *internal* modules, which a bad merge can leave dangling. It is shallow
    by design — dependency completeness against pyproject.toml is deptry's
    static job.
    """
    pkg_name = "python_copier_template_example"
    for name in _package_modules():
        try:
            importlib.import_module(name)
        except ImportError as exc:
            missing = exc.name or ""
            if missing == pkg_name or missing.startswith(f"{pkg_name}."):
                raise


def test_deidentification_guardrails_present() -> None:
    """De-identification bar ships with the data layout (ISO 20889 / GDPR R26).

    DEIDENTIFICATION.md states the rule; sharing/TRANSFER_LOG.csv records
    every external transfer; DATA_TRANSFER_AGREEMENT.md gates restricted
    moves. A data tree without this trio can ship extracts with no paper
    trail, so the QA suite fails first.
    """
    assert (TOP / "data" / "DEIDENTIFICATION.md").exists()
    assert (TOP / "data" / "sharing" / "DATA_TRANSFER_AGREEMENT.md").exists()
    log = TOP / "data" / "sharing" / "TRANSFER_LOG.csv"
    assert log.exists()
    header = log.read_text(encoding="utf-8").splitlines()[0]
    for column in ("recipient", "sha256", "authorized_by", "deletion_confirmed"):
        assert column in header, f"TRANSFER_LOG.csv lost column {column!r}"


def test_no_deidentification_salt_committed() -> None:
    """No pseudonymisation salt may be committed (gitleaks is the backstop).

    DEIDENTIFICATION.md requires the HMAC salt to stay out of the repo.
    This offline sweep mirrors the gitleaks `deidentification-salt` rule
    so `task test` catches a committed salt without needing the hook.
    """
    import re

    pattern = re.compile(r"(?i)\b(secret|deidentification|pseudonym)_salt\s*=\s*\S+")
    offenders = [
        str(p)
        for p in TOP.rglob("*")
        if p.is_file()
        and ".git/" not in p.as_posix()
        and ".venv/" not in p.as_posix()
        and pattern.search(p.read_text(encoding="utf-8", errors="ignore"))
    ]
    assert not offenders, f"de-identification salt committed in: {offenders}"


def test_citation_metadata_present() -> None:
    """FAIR opt-in ships machine-readable citation metadata."""
    assert (TOP / "CITATION.cff").exists()


def test_spdx_annotations_present() -> None:
    """Open-source FAIR opt-in ships aggregate SPDX annotations."""
    reuse = (TOP / "REUSE.toml").read_text(encoding="utf-8")
    assert 'SPDX-License-Identifier = "Apache-2.0"' in reuse
